compiler/natives/src/net: Implement missing private helpers.
This change makes net package compile, and allows crypto/x509
tests to pass.

Fixes:

	$ gopherjs test --short crypto/x509
	--- FAIL: TestMatchIP (0.00s)

	Error: runtime error: native function not implemented: net.bytesEqual