compiler/natives/src/internal/poll: Create no-op I/O poller implementation.
gopherjs test uses tempFile to create temporary files during execution
of examples. tempFile calls os.OpenFile to create a file. os.OpenFile
calls newFile, which in Go 1.9 tries to add the file to the runtime
poller.

Normally, on OSes like darwin, linux, etc., this tries to use a real
runtime poller from internal/poll package. We override that package
so that a no-op implementation (based on NaCL implementation) is used
instead.

Fixes:

	Error: runtime error: native function not implemented: internal/poll.runtime_pollServerInit

After this change, some basic tests pass:

	$ gopherjs test errors github.com/gopherjs/gopherjs/tests
	PASS
	ok  	errors	0.453s
	PASS
	ok  	github.com/gopherjs/gopherjs/tests	0.606s