compiler/natives/src/time: Add initial support for monotonic clock.
For now, just keep using Date.getTime as a monotonic clock.
If there's a better choice (perhaps window.performance.now()),
it can be substituted later.

Fixes:

	$ go install -tags=gopherjsdev -v && touch $(which gopherjs) && gopherjs test --short time
	--- FAIL: TestHasMonotonicClock (0.00s)
		mono_test.go:16: <-After(1): missing monotonic clock reading
		mono_test.go:16: <-Tick(1): missing monotonic clock reading
		mono_test.go:16: Now(): missing monotonic clock reading
	--- FAIL: TestSleep (0.00s)
		sleep_test.go:40: Sleep(100ms) slept for only 0s
	--- FAIL: TestAfter (0.00s)
		sleep_test.go:170: After(100ms) slept for only 0 ns
	--- FAIL: TestAfterTick (0.00s)
		sleep_test.go:191: 10 ticks of 10ms too fast: took 0s, expected 100ms
	--- FAIL: TestAfterQueuing (0.00s)
		sleep_test.go:231: attempt 0 failed: After(20ms) arrived at 0s, expected [10ms,220ms]
		sleep_test.go:231: attempt 1 failed: After(70ms) arrived at 0s, expected [35ms,770ms]
		sleep_test.go:231: attempt 2 failed: After(120ms) arrived at 0s, expected [60ms,1.32s]
		sleep_test.go:231: attempt 3 failed: After(170ms) arrived at 0s, expected [85ms,1.87s]
		sleep_test.go:231: attempt 4 failed: After(220ms) arrived at 0s, expected [110ms,2.42s]
		sleep_test.go:235: After(220ms) arrived at 0s, expected [110ms,2.42s]
	--- FAIL: TestTicker (0.00s)
		tick_test.go:26: 10 100ms ticks took 0s, expected [800ms,1.2s]
	FAIL
	FAIL	time	13.658s