compiler/natives/src/math: Implement missing functions.
This change makes all math tests pass.

Fixes:

	$ gopherjs test --short math
	--- FAIL: TestAcosh (0.00s)

	Error: runtime error: native function not implemented: math.Acosh